medbot:
  database:
    host: 'sql624.main-hosting.eu'
    database: 'u234071176_medbot'
    user: 'u234071176_medbot'
    password: 'Medbot@2022'
  settings:
    voice_command: true
    voice_prompt: true
  speaker:
    id: 'english'
    language: 'english'
    rate: 20 # default: 130
    volume: 1 # default: 1
    voice: 'male' # values: 'male' or 'female'
  microphone:
    index: 2
  gui:
    body_check_prompt:
      text: 'Please position your arm correctly'
      voice: Please position your arm correctly'
    in_progress_prompt:
      text: 'Measuring your vital signs. Please stay still'
      voice: 'Measuring your vital signs. Please stay still'
    vital_signs_indicator:
      low: 'Your vital signs are below than what is supposed to be normal. You should consult your doctor immediately'
      normal: 'Your vital signs seems normal. You should be fine for now'
      high: 'Your vitals signs seems higher than normal. You should consult your doctor immediately'
    printer_prompt:
      text: 'Print results?'
      accepted_answers:
        - 'yes'
        - 'no'
      on_failure_message: 'Please respond with yes or no'
      
    